# Dependencies
markdown: kramdown

# Custom vars
project_name: rangeslider.js
current_version: 0.3.1
repository_url: https://github.com/andreruffert/rangeslider.js

exclude:
- "bower.json"
- "Gemfile"
- "README.md"
