# Dependencies
markdown: kramdown

# Custom vars
project_name: rangeslider.js
current_version: 1.3.3
repository_url: https://github.com/andreruffert/rangeslider.js
baseurl: /rangeslider.js

exclude:
- "bower.json"
- "Gemfile"
- "README.md"

sass:
    sass_dir: _includes/scss
    style: :compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
