# Dependencies
markdown: kramdown

# Custom vars
project_name: rangeslider.js
current_version: 1.2.0
repository_url: https://github.com/andreruffert/rangeslider.js
baseurl: /rangeslider.js

exclude:
- "bower.json"
- "Gemfile"
- "README.md"

sass:
    style: :compressed
